version: '3'
services:
    web:
        build: .
        container_name: web
        ports:
            - 3000:3000
        networks:
            - nodeapp
        environment:
            - EV_PORT=3000
            - EV_HOST=0.0.0.0
            - DB_HOST=mongo
            - DB_PORT=27017
            - DB_NAME=jwt-auth
            - ENV=production
            - JWT_SECRET=486f805PXd0k705c9q5EZ95yF
        volumes:
            - './src:/app/src'
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/mongodb
        ports:
            - '27017:27017'
        networks:
            - nodeapp
networks:
    nodeapp:
        driver: bridge
